"""set column level in roles

Revision ID: 7981f7f2c698
Revises: f8a6c22c91e1
Create Date: 2024-04-16 15:46:35.095833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import RoleORM


# revision identifiers, used by Alembic.
revision: str = '7981f7f2c698'
down_revision: Union[str, None] = 'f8a6c22c91e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('level', sa.Integer(), nullable=True))
    op.execute(sa.update(RoleORM).where(RoleORM.level == None).values(level=0))
    op.alter_column("roles", "level", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'level')
    # ### end Alembic commands ###
