"""add org_id column

Revision ID: dfd288a55201
Revises: 7981f7f2c698
Create Date: 2024-04-19 14:50:46.256311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd288a55201'
down_revision: Union[str, None] = '7981f7f2c698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_foreign_key("structures_org_fkey", 'structures', 'structures', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("structures_org_fkey", 'structures', type_='foreignkey')
    op.drop_column('structures', 'org_id')
    # ### end Alembic commands ###
