"""set head_id nullable

Revision ID: f8a6c22c91e1
Revises: 1775dbf6761b
Create Date: 2024-04-16 14:22:03.692616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.roles import RoleORM
from models.structures import StructureORM


# revision identifiers, used by Alembic.
revision: str = 'f8a6c22c91e1'
down_revision: Union[str, None] = '1775dbf6761b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('structures', 'head_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('structures_head_id_fkey', 'structures', type_='foreignkey')
    op.create_foreign_key("structures_head_id_fkey", 'structures', 'roles', ['head_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("structures_head_id_fkey", 'structures', type_='foreignkey')
    op.create_foreign_key('structures_head_id_fkey', 'structures', 'roles', ['head_id'], ['id'])
    op.execute(sa.delete(StructureORM).where(StructureORM.head_id==None))
    op.alter_column('structures', 'head_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
